# Generated by Django 3.2.16 on 2022-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default='Unmanaged', on_delete=models.SET('Unmanaged'), to='home.owner', to_field='full_name'),
        ),
    ]
