# Generated by Django 3.2.16 on 2022-11-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_owner_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=15)),
                ('sec_function', models.TextField()),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('subarea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='requisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('typology', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSA', models.CharField(max_length=15)),
                ('funct_referent', models.CharField(max_length=50)),
                ('tech_referent', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=15)),
                ('product_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=50)),
                ('subarea', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('enduser', models.CharField(max_length=15)),
                ('end_of_life', models.DateField(blank=True)),
                ('end_of_support', models.DateField(blank=True)),
                ('vendor', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('DR', models.CharField(max_length=20)),
                ('HA', models.CharField(max_length=20)),
                ('DRHA_solution', models.CharField(max_length=20)),
                ('RTO', models.CharField(max_length=20)),
                ('last_update', models.DateField(blank=True)),
                ('sec_function', models.TextField()),
            ],
        ),
    ]
