# Generated by Django 3.2.16 on 2022-11-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_function_requisite_test_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='end_of_life',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='end_of_support',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
