# Generated by Django 3.2.16 on 2022-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
