# Generated by Django 3.2.16 on 2022-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_tool_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='DRHA_solution',
            field=models.CharField(max_length=70),
        ),
    ]
