# Generated by Django 3.2.16 on 2022-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_tool_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='DR',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='HA',
            field=models.CharField(max_length=50),
        ),
    ]
