# Generated by Django 3.2.16 on 2022-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221123_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='vendor',
            field=models.CharField(max_length=50),
        ),
    ]
