# Generated by Django 3.2.16 on 2022-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_tool_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='department',
        ),
        migrations.AlterField(
            model_name='function',
            name='sec_function',
            field=models.CharField(max_length=150),
        ),
    ]
