# Generated by Django 3.2.16 on 2022-12-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('note', models.TextField()),
                ('typology', models.CharField(max_length=50)),
            ],
        ),
    ]
