# Generated by Django 3.2.16 on 2022-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='implementation',
        ),
        migrations.AddField(
            model_name='project',
            name='approval',
            field=models.CharField(default='Not Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
